### ISSUE TITLE
Is this published?

### ISSUE THREAD

**Issue by benadamstyles** [owensd/vscode-swift#1]
First of all, sorry if I'm missing something obvious. I *think* this hasn't been published to the vscode marketplace yet, but I just wanted to double check. I can't find it anyway. If it isn't yet, I'm very much looking forward to it!

**Comment by owensd** [comment]
Not yet! I'm looking at getting this published by the end of the week. It's still in its infancy, but I want to get a few more things in place, some testing as I know there are crashes when you don't have the happy path, and to make the macOS installation at least, super simple.

**Comment by benadamstyles** [comment]
Ace, thanks. Let me know if there's anything I can do to help.
