### ISSUE TITLE
Doesn't show up in the marketplace

### ISSUE THREAD

**Issue by alexito4** [owensd/vscode-swift#2]
Searching for `Swift for Visual Studio Code` like the README suggest doesn't show this extension, at least to me. I locked at the package.json and saw that the name is Apous, that works perfectly. First result 👍 
Maybe indicating it in the READMR would be useful 😉

**Comment by owensd** [comment]
Good catch. I renamed it a few times and forgot to update the README. I'll update.

**Comment by owensd** [comment]
Fixed with v0.5.3
